//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace WinService_ImportacaoMGI2.XSD {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("Contrato")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class Contrato : global::System.Data.DataSet {
        
        private dtbContratoDataTable tabledtbContrato;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public Contrato() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected Contrato(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["dtbContrato"] != null)) {
                    base.Tables.Add(new dtbContratoDataTable(ds.Tables["dtbContrato"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public dtbContratoDataTable dtbContrato {
            get {
                return this.tabledtbContrato;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            Contrato cln = ((Contrato)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["dtbContrato"] != null)) {
                    base.Tables.Add(new dtbContratoDataTable(ds.Tables["dtbContrato"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tabledtbContrato = ((dtbContratoDataTable)(base.Tables["dtbContrato"]));
            if ((initTable == true)) {
                if ((this.tabledtbContrato != null)) {
                    this.tabledtbContrato.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "Contrato";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/Contrato.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tabledtbContrato = new dtbContratoDataTable();
            base.Tables.Add(this.tabledtbContrato);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializedtbContrato() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            Contrato ds = new Contrato();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void dtbContratoRowChangeEventHandler(object sender, dtbContratoRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class dtbContratoDataTable : global::System.Data.TypedTableBase<dtbContratoRow> {
            
            private global::System.Data.DataColumn columnID_Contrato;
            
            private global::System.Data.DataColumn columnCod_Empresa_Faturamento;
            
            private global::System.Data.DataColumn columnNumero_Negociacao;
            
            private global::System.Data.DataColumn columnCod_Empresa;
            
            private global::System.Data.DataColumn columnNumero_Mr;
            
            private global::System.Data.DataColumn columnSequencia_Mr;
            
            private global::System.Data.DataColumn columnCompetencia;
            
            private global::System.Data.DataColumn columnCod_Tipo_Midia;
            
            private global::System.Data.DataColumn columnCod_Agencia;
            
            private global::System.Data.DataColumn columnCod_Cliente;
            
            private global::System.Data.DataColumn columnCod_Intermediario;
            
            private global::System.Data.DataColumn columnCod_Nucleo;
            
            private global::System.Data.DataColumn columnCod_Contato;
            
            private global::System.Data.DataColumn columnIndica_Grade;
            
            private global::System.Data.DataColumn columnIndica_Midia;
            
            private global::System.Data.DataColumn columnIndica_Desvinculado;
            
            private global::System.Data.DataColumn columnIndica_Cancelado;
            
            private global::System.Data.DataColumn columnMotivo_Cancelamento;
            
            private global::System.Data.DataColumn columnCod_Programa_Patrocinado;
            
            private global::System.Data.DataColumn columnComissao_Agencia;
            
            private global::System.Data.DataColumn columnComissao_Intermediario;
            
            private global::System.Data.DataColumn columnData_Cadastramento;
            
            private global::System.Data.DataColumn columnNumero_PI;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dtbContratoDataTable() {
                this.TableName = "dtbContrato";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal dtbContratoDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected dtbContratoDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ID_ContratoColumn {
                get {
                    return this.columnID_Contrato;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Cod_Empresa_FaturamentoColumn {
                get {
                    return this.columnCod_Empresa_Faturamento;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Numero_NegociacaoColumn {
                get {
                    return this.columnNumero_Negociacao;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Cod_EmpresaColumn {
                get {
                    return this.columnCod_Empresa;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Numero_MrColumn {
                get {
                    return this.columnNumero_Mr;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Sequencia_MrColumn {
                get {
                    return this.columnSequencia_Mr;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn CompetenciaColumn {
                get {
                    return this.columnCompetencia;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Cod_Tipo_MidiaColumn {
                get {
                    return this.columnCod_Tipo_Midia;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Cod_AgenciaColumn {
                get {
                    return this.columnCod_Agencia;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Cod_ClienteColumn {
                get {
                    return this.columnCod_Cliente;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Cod_IntermediarioColumn {
                get {
                    return this.columnCod_Intermediario;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Cod_NucleoColumn {
                get {
                    return this.columnCod_Nucleo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Cod_ContatoColumn {
                get {
                    return this.columnCod_Contato;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Indica_GradeColumn {
                get {
                    return this.columnIndica_Grade;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Indica_MidiaColumn {
                get {
                    return this.columnIndica_Midia;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Indica_DesvinculadoColumn {
                get {
                    return this.columnIndica_Desvinculado;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Indica_CanceladoColumn {
                get {
                    return this.columnIndica_Cancelado;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Motivo_CancelamentoColumn {
                get {
                    return this.columnMotivo_Cancelamento;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Cod_Programa_PatrocinadoColumn {
                get {
                    return this.columnCod_Programa_Patrocinado;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Comissao_AgenciaColumn {
                get {
                    return this.columnComissao_Agencia;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Comissao_IntermediarioColumn {
                get {
                    return this.columnComissao_Intermediario;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Data_CadastramentoColumn {
                get {
                    return this.columnData_Cadastramento;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Numero_PIColumn {
                get {
                    return this.columnNumero_PI;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dtbContratoRow this[int index] {
                get {
                    return ((dtbContratoRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dtbContratoRowChangeEventHandler dtbContratoRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dtbContratoRowChangeEventHandler dtbContratoRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dtbContratoRowChangeEventHandler dtbContratoRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dtbContratoRowChangeEventHandler dtbContratoRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AdddtbContratoRow(dtbContratoRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dtbContratoRow AdddtbContratoRow(
                        string Cod_Empresa_Faturamento, 
                        decimal Numero_Negociacao, 
                        string Cod_Empresa, 
                        int Numero_Mr, 
                        short Sequencia_Mr, 
                        int Competencia, 
                        string Cod_Tipo_Midia, 
                        string Cod_Agencia, 
                        string Cod_Cliente, 
                        string Cod_Intermediario, 
                        string Cod_Nucleo, 
                        string Cod_Contato, 
                        byte Indica_Grade, 
                        byte Indica_Midia, 
                        byte Indica_Desvinculado, 
                        byte Indica_Cancelado, 
                        string Motivo_Cancelamento, 
                        string Cod_Programa_Patrocinado, 
                        decimal Comissao_Agencia, 
                        decimal Comissao_Intermediario, 
                        System.DateTime Data_Cadastramento, 
                        string Numero_PI) {
                dtbContratoRow rowdtbContratoRow = ((dtbContratoRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        null,
                        Cod_Empresa_Faturamento,
                        Numero_Negociacao,
                        Cod_Empresa,
                        Numero_Mr,
                        Sequencia_Mr,
                        Competencia,
                        Cod_Tipo_Midia,
                        Cod_Agencia,
                        Cod_Cliente,
                        Cod_Intermediario,
                        Cod_Nucleo,
                        Cod_Contato,
                        Indica_Grade,
                        Indica_Midia,
                        Indica_Desvinculado,
                        Indica_Cancelado,
                        Motivo_Cancelamento,
                        Cod_Programa_Patrocinado,
                        Comissao_Agencia,
                        Comissao_Intermediario,
                        Data_Cadastramento,
                        Numero_PI};
                rowdtbContratoRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowdtbContratoRow);
                return rowdtbContratoRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                dtbContratoDataTable cln = ((dtbContratoDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new dtbContratoDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnID_Contrato = base.Columns["ID_Contrato"];
                this.columnCod_Empresa_Faturamento = base.Columns["Cod_Empresa_Faturamento"];
                this.columnNumero_Negociacao = base.Columns["Numero_Negociacao"];
                this.columnCod_Empresa = base.Columns["Cod_Empresa"];
                this.columnNumero_Mr = base.Columns["Numero_Mr"];
                this.columnSequencia_Mr = base.Columns["Sequencia_Mr"];
                this.columnCompetencia = base.Columns["Competencia"];
                this.columnCod_Tipo_Midia = base.Columns["Cod_Tipo_Midia"];
                this.columnCod_Agencia = base.Columns["Cod_Agencia"];
                this.columnCod_Cliente = base.Columns["Cod_Cliente"];
                this.columnCod_Intermediario = base.Columns["Cod_Intermediario"];
                this.columnCod_Nucleo = base.Columns["Cod_Nucleo"];
                this.columnCod_Contato = base.Columns["Cod_Contato"];
                this.columnIndica_Grade = base.Columns["Indica_Grade"];
                this.columnIndica_Midia = base.Columns["Indica_Midia"];
                this.columnIndica_Desvinculado = base.Columns["Indica_Desvinculado"];
                this.columnIndica_Cancelado = base.Columns["Indica_Cancelado"];
                this.columnMotivo_Cancelamento = base.Columns["Motivo_Cancelamento"];
                this.columnCod_Programa_Patrocinado = base.Columns["Cod_Programa_Patrocinado"];
                this.columnComissao_Agencia = base.Columns["Comissao_Agencia"];
                this.columnComissao_Intermediario = base.Columns["Comissao_Intermediario"];
                this.columnData_Cadastramento = base.Columns["Data_Cadastramento"];
                this.columnNumero_PI = base.Columns["Numero_PI"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnID_Contrato = new global::System.Data.DataColumn("ID_Contrato", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnID_Contrato);
                this.columnCod_Empresa_Faturamento = new global::System.Data.DataColumn("Cod_Empresa_Faturamento", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCod_Empresa_Faturamento);
                this.columnNumero_Negociacao = new global::System.Data.DataColumn("Numero_Negociacao", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNumero_Negociacao);
                this.columnCod_Empresa = new global::System.Data.DataColumn("Cod_Empresa", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCod_Empresa);
                this.columnNumero_Mr = new global::System.Data.DataColumn("Numero_Mr", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNumero_Mr);
                this.columnSequencia_Mr = new global::System.Data.DataColumn("Sequencia_Mr", typeof(short), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSequencia_Mr);
                this.columnCompetencia = new global::System.Data.DataColumn("Competencia", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCompetencia);
                this.columnCod_Tipo_Midia = new global::System.Data.DataColumn("Cod_Tipo_Midia", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCod_Tipo_Midia);
                this.columnCod_Agencia = new global::System.Data.DataColumn("Cod_Agencia", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCod_Agencia);
                this.columnCod_Cliente = new global::System.Data.DataColumn("Cod_Cliente", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCod_Cliente);
                this.columnCod_Intermediario = new global::System.Data.DataColumn("Cod_Intermediario", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCod_Intermediario);
                this.columnCod_Nucleo = new global::System.Data.DataColumn("Cod_Nucleo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCod_Nucleo);
                this.columnCod_Contato = new global::System.Data.DataColumn("Cod_Contato", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCod_Contato);
                this.columnIndica_Grade = new global::System.Data.DataColumn("Indica_Grade", typeof(byte), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIndica_Grade);
                this.columnIndica_Midia = new global::System.Data.DataColumn("Indica_Midia", typeof(byte), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIndica_Midia);
                this.columnIndica_Desvinculado = new global::System.Data.DataColumn("Indica_Desvinculado", typeof(byte), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIndica_Desvinculado);
                this.columnIndica_Cancelado = new global::System.Data.DataColumn("Indica_Cancelado", typeof(byte), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIndica_Cancelado);
                this.columnMotivo_Cancelamento = new global::System.Data.DataColumn("Motivo_Cancelamento", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMotivo_Cancelamento);
                this.columnCod_Programa_Patrocinado = new global::System.Data.DataColumn("Cod_Programa_Patrocinado", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCod_Programa_Patrocinado);
                this.columnComissao_Agencia = new global::System.Data.DataColumn("Comissao_Agencia", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnComissao_Agencia);
                this.columnComissao_Intermediario = new global::System.Data.DataColumn("Comissao_Intermediario", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnComissao_Intermediario);
                this.columnData_Cadastramento = new global::System.Data.DataColumn("Data_Cadastramento", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnData_Cadastramento);
                this.columnNumero_PI = new global::System.Data.DataColumn("Numero_PI", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNumero_PI);
                this.columnID_Contrato.AutoIncrement = true;
                this.columnID_Contrato.AllowDBNull = false;
                this.columnID_Contrato.ReadOnly = true;
                this.columnCod_Empresa_Faturamento.AllowDBNull = false;
                this.columnNumero_Negociacao.AllowDBNull = false;
                this.columnCod_Empresa.AllowDBNull = false;
                this.columnNumero_Mr.AllowDBNull = false;
                this.columnSequencia_Mr.AllowDBNull = false;
                this.columnCompetencia.AllowDBNull = false;
                this.columnCod_Tipo_Midia.AllowDBNull = false;
                this.columnCod_Agencia.AllowDBNull = false;
                this.columnCod_Cliente.AllowDBNull = false;
                this.columnCod_Nucleo.AllowDBNull = false;
                this.columnCod_Contato.AllowDBNull = false;
                this.columnIndica_Grade.AllowDBNull = false;
                this.columnIndica_Midia.AllowDBNull = false;
                this.columnIndica_Desvinculado.AllowDBNull = false;
                this.columnIndica_Cancelado.AllowDBNull = false;
                this.columnMotivo_Cancelamento.AllowDBNull = false;
                this.columnComissao_Agencia.AllowDBNull = false;
                this.columnComissao_Intermediario.AllowDBNull = false;
                this.columnData_Cadastramento.AllowDBNull = false;
                this.columnNumero_PI.AllowDBNull = false;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dtbContratoRow NewdtbContratoRow() {
                return ((dtbContratoRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new dtbContratoRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(dtbContratoRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.dtbContratoRowChanged != null)) {
                    this.dtbContratoRowChanged(this, new dtbContratoRowChangeEvent(((dtbContratoRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.dtbContratoRowChanging != null)) {
                    this.dtbContratoRowChanging(this, new dtbContratoRowChangeEvent(((dtbContratoRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.dtbContratoRowDeleted != null)) {
                    this.dtbContratoRowDeleted(this, new dtbContratoRowChangeEvent(((dtbContratoRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.dtbContratoRowDeleting != null)) {
                    this.dtbContratoRowDeleting(this, new dtbContratoRowChangeEvent(((dtbContratoRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemovedtbContratoRow(dtbContratoRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                Contrato ds = new Contrato();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "dtbContratoDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class dtbContratoRow : global::System.Data.DataRow {
            
            private dtbContratoDataTable tabledtbContrato;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal dtbContratoRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tabledtbContrato = ((dtbContratoDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int ID_Contrato {
                get {
                    return ((int)(this[this.tabledtbContrato.ID_ContratoColumn]));
                }
                set {
                    this[this.tabledtbContrato.ID_ContratoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Cod_Empresa_Faturamento {
                get {
                    return ((string)(this[this.tabledtbContrato.Cod_Empresa_FaturamentoColumn]));
                }
                set {
                    this[this.tabledtbContrato.Cod_Empresa_FaturamentoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal Numero_Negociacao {
                get {
                    return ((decimal)(this[this.tabledtbContrato.Numero_NegociacaoColumn]));
                }
                set {
                    this[this.tabledtbContrato.Numero_NegociacaoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Cod_Empresa {
                get {
                    return ((string)(this[this.tabledtbContrato.Cod_EmpresaColumn]));
                }
                set {
                    this[this.tabledtbContrato.Cod_EmpresaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int Numero_Mr {
                get {
                    return ((int)(this[this.tabledtbContrato.Numero_MrColumn]));
                }
                set {
                    this[this.tabledtbContrato.Numero_MrColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public short Sequencia_Mr {
                get {
                    return ((short)(this[this.tabledtbContrato.Sequencia_MrColumn]));
                }
                set {
                    this[this.tabledtbContrato.Sequencia_MrColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int Competencia {
                get {
                    return ((int)(this[this.tabledtbContrato.CompetenciaColumn]));
                }
                set {
                    this[this.tabledtbContrato.CompetenciaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Cod_Tipo_Midia {
                get {
                    return ((string)(this[this.tabledtbContrato.Cod_Tipo_MidiaColumn]));
                }
                set {
                    this[this.tabledtbContrato.Cod_Tipo_MidiaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Cod_Agencia {
                get {
                    return ((string)(this[this.tabledtbContrato.Cod_AgenciaColumn]));
                }
                set {
                    this[this.tabledtbContrato.Cod_AgenciaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Cod_Cliente {
                get {
                    return ((string)(this[this.tabledtbContrato.Cod_ClienteColumn]));
                }
                set {
                    this[this.tabledtbContrato.Cod_ClienteColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Cod_Intermediario {
                get {
                    try {
                        return ((string)(this[this.tabledtbContrato.Cod_IntermediarioColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Cod_Intermediario\' in table \'dtbContrato\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledtbContrato.Cod_IntermediarioColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Cod_Nucleo {
                get {
                    return ((string)(this[this.tabledtbContrato.Cod_NucleoColumn]));
                }
                set {
                    this[this.tabledtbContrato.Cod_NucleoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Cod_Contato {
                get {
                    return ((string)(this[this.tabledtbContrato.Cod_ContatoColumn]));
                }
                set {
                    this[this.tabledtbContrato.Cod_ContatoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public byte Indica_Grade {
                get {
                    return ((byte)(this[this.tabledtbContrato.Indica_GradeColumn]));
                }
                set {
                    this[this.tabledtbContrato.Indica_GradeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public byte Indica_Midia {
                get {
                    return ((byte)(this[this.tabledtbContrato.Indica_MidiaColumn]));
                }
                set {
                    this[this.tabledtbContrato.Indica_MidiaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public byte Indica_Desvinculado {
                get {
                    return ((byte)(this[this.tabledtbContrato.Indica_DesvinculadoColumn]));
                }
                set {
                    this[this.tabledtbContrato.Indica_DesvinculadoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public byte Indica_Cancelado {
                get {
                    return ((byte)(this[this.tabledtbContrato.Indica_CanceladoColumn]));
                }
                set {
                    this[this.tabledtbContrato.Indica_CanceladoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Motivo_Cancelamento {
                get {
                    return ((string)(this[this.tabledtbContrato.Motivo_CancelamentoColumn]));
                }
                set {
                    this[this.tabledtbContrato.Motivo_CancelamentoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Cod_Programa_Patrocinado {
                get {
                    try {
                        return ((string)(this[this.tabledtbContrato.Cod_Programa_PatrocinadoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Cod_Programa_Patrocinado\' in table \'dtbContrato\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tabledtbContrato.Cod_Programa_PatrocinadoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal Comissao_Agencia {
                get {
                    return ((decimal)(this[this.tabledtbContrato.Comissao_AgenciaColumn]));
                }
                set {
                    this[this.tabledtbContrato.Comissao_AgenciaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal Comissao_Intermediario {
                get {
                    return ((decimal)(this[this.tabledtbContrato.Comissao_IntermediarioColumn]));
                }
                set {
                    this[this.tabledtbContrato.Comissao_IntermediarioColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime Data_Cadastramento {
                get {
                    return ((global::System.DateTime)(this[this.tabledtbContrato.Data_CadastramentoColumn]));
                }
                set {
                    this[this.tabledtbContrato.Data_CadastramentoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Numero_PI {
                get {
                    return ((string)(this[this.tabledtbContrato.Numero_PIColumn]));
                }
                set {
                    this[this.tabledtbContrato.Numero_PIColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCod_IntermediarioNull() {
                return this.IsNull(this.tabledtbContrato.Cod_IntermediarioColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCod_IntermediarioNull() {
                this[this.tabledtbContrato.Cod_IntermediarioColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCod_Programa_PatrocinadoNull() {
                return this.IsNull(this.tabledtbContrato.Cod_Programa_PatrocinadoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCod_Programa_PatrocinadoNull() {
                this[this.tabledtbContrato.Cod_Programa_PatrocinadoColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class dtbContratoRowChangeEvent : global::System.EventArgs {
            
            private dtbContratoRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dtbContratoRowChangeEvent(dtbContratoRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dtbContratoRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591